///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BambooTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BambooTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("b24f02f0-15cd-4841-b040-51634afbe633")]
    public partial class BambooTestRepository : RepoGenBaseFolder
    {
        static BambooTestRepository instance = new BambooTestRepository();
        BambooTestRepositoryFolders.RanorexWebpageAppFolder _ranorexwebpage;

        /// <summary>
        /// Gets the singleton class instance representing the BambooTestRepository element repository.
        /// </summary>
        [RepositoryFolder("b24f02f0-15cd-4841-b040-51634afbe633")]
        public static BambooTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BambooTestRepository() 
            : base("BambooTestRepository", "/", null, 0, false, "b24f02f0-15cd-4841-b040-51634afbe633", ".\\RepositoryImages\\BambooTestRepositoryb24f02f0.rximgres")
        {
            _ranorexwebpage = new BambooTestRepositoryFolders.RanorexWebpageAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b24f02f0-15cd-4841-b040-51634afbe633")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexWebpage folder.
        /// </summary>
        [RepositoryFolder("0a4028cd-0a11-460b-85c7-fc770bb16c7e")]
        public virtual BambooTestRepositoryFolders.RanorexWebpageAppFolder RanorexWebpage
        {
            get { return _ranorexwebpage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class BambooTestRepositoryFolders
    {
        /// <summary>
        /// The RanorexWebpageAppFolder folder.
        /// </summary>
        [RepositoryFolder("0a4028cd-0a11-460b-85c7-fc770bb16c7e")]
        public partial class RanorexWebpageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorextestautomationInfo;
            RepoItemInfo _downloadlinkInfo;
            RepoItemInfo _formemailInfo;
            RepoItemInfo _formfirstnameInfo;
            RepoItemInfo _formlastnameInfo;
            RepoItemInfo _registerInfo;
            RepoItemInfo _iconexitInfo;

            /// <summary>
            /// Creates a new RanorexWebpage  folder.
            /// </summary>
            public RanorexWebpageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexWebpage", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "0a4028cd-0a11-460b-85c7-fc770bb16c7e", "")
            {
                _ranorextestautomationInfo = new RepoItemInfo(this, "RanorexTestAutomation", ".//div[#'main-nav']//img[@alt='Ranorex test automation']", 30000, null, "4e8f41f4-1ac0-43b5-a209-2e13a6d89654");
                _downloadlinkInfo = new RepoItemInfo(this, "DownloadLink", ".//a[#'download-link']", 30000, null, "3fb9cd16-dd37-4620-820c-b13a376373cc");
                _formemailInfo = new RepoItemInfo(this, "FormEmail", ".//input[#'form-Email']", 30000, null, "b97f47ed-fff3-42d1-9adc-0b7373a657c8");
                _formfirstnameInfo = new RepoItemInfo(this, "FormFirstName", ".//input[#'form-FirstName']", 30000, null, "4ca49f11-8b10-4da5-b201-14c6c8a88d29");
                _formlastnameInfo = new RepoItemInfo(this, "FormLastName", ".//input[#'form-LastName']", 30000, null, "bce8c729-7f8e-4d35-95c0-435ecd7e586c");
                _registerInfo = new RepoItemInfo(this, "Register", ".//fieldset[#'first-form']/?/?/button[@innertext='Register']", 30000, null, "9cdf99fd-af8d-4f8b-81b7-1c26387d10af");
                _iconexitInfo = new RepoItemInfo(this, "IconExit", ".//fieldset[#'first-form']//span", 30000, null, "8142e401-eb9f-4017-89f8-d758426a7fef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a4028cd-0a11-460b-85c7-fc770bb16c7e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a4028cd-0a11-460b-85c7-fc770bb16c7e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexTestAutomation item.
            /// </summary>
            [RepositoryItem("4e8f41f4-1ac0-43b5-a209-2e13a6d89654")]
            public virtual Ranorex.ImgTag RanorexTestAutomation
            {
                get
                {
                    return _ranorextestautomationInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The RanorexTestAutomation item info.
            /// </summary>
            [RepositoryItemInfo("4e8f41f4-1ac0-43b5-a209-2e13a6d89654")]
            public virtual RepoItemInfo RanorexTestAutomationInfo
            {
                get
                {
                    return _ranorextestautomationInfo;
                }
            }

            /// <summary>
            /// The DownloadLink item.
            /// </summary>
            [RepositoryItem("3fb9cd16-dd37-4620-820c-b13a376373cc")]
            public virtual Ranorex.ATag DownloadLink
            {
                get
                {
                    return _downloadlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DownloadLink item info.
            /// </summary>
            [RepositoryItemInfo("3fb9cd16-dd37-4620-820c-b13a376373cc")]
            public virtual RepoItemInfo DownloadLinkInfo
            {
                get
                {
                    return _downloadlinkInfo;
                }
            }

            /// <summary>
            /// The FormEmail item.
            /// </summary>
            [RepositoryItem("b97f47ed-fff3-42d1-9adc-0b7373a657c8")]
            public virtual Ranorex.InputTag FormEmail
            {
                get
                {
                    return _formemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FormEmail item info.
            /// </summary>
            [RepositoryItemInfo("b97f47ed-fff3-42d1-9adc-0b7373a657c8")]
            public virtual RepoItemInfo FormEmailInfo
            {
                get
                {
                    return _formemailInfo;
                }
            }

            /// <summary>
            /// The FormFirstName item.
            /// </summary>
            [RepositoryItem("4ca49f11-8b10-4da5-b201-14c6c8a88d29")]
            public virtual Ranorex.InputTag FormFirstName
            {
                get
                {
                    return _formfirstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FormFirstName item info.
            /// </summary>
            [RepositoryItemInfo("4ca49f11-8b10-4da5-b201-14c6c8a88d29")]
            public virtual RepoItemInfo FormFirstNameInfo
            {
                get
                {
                    return _formfirstnameInfo;
                }
            }

            /// <summary>
            /// The FormLastName item.
            /// </summary>
            [RepositoryItem("bce8c729-7f8e-4d35-95c0-435ecd7e586c")]
            public virtual Ranorex.InputTag FormLastName
            {
                get
                {
                    return _formlastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FormLastName item info.
            /// </summary>
            [RepositoryItemInfo("bce8c729-7f8e-4d35-95c0-435ecd7e586c")]
            public virtual RepoItemInfo FormLastNameInfo
            {
                get
                {
                    return _formlastnameInfo;
                }
            }

            /// <summary>
            /// The Register item.
            /// </summary>
            [RepositoryItem("9cdf99fd-af8d-4f8b-81b7-1c26387d10af")]
            public virtual Ranorex.ButtonTag Register
            {
                get
                {
                    return _registerInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Register item info.
            /// </summary>
            [RepositoryItemInfo("9cdf99fd-af8d-4f8b-81b7-1c26387d10af")]
            public virtual RepoItemInfo RegisterInfo
            {
                get
                {
                    return _registerInfo;
                }
            }

            /// <summary>
            /// The IconExit item.
            /// </summary>
            [RepositoryItem("8142e401-eb9f-4017-89f8-d758426a7fef")]
            public virtual Ranorex.SpanTag IconExit
            {
                get
                {
                    return _iconexitInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The IconExit item info.
            /// </summary>
            [RepositoryItemInfo("8142e401-eb9f-4017-89f8-d758426a7fef")]
            public virtual RepoItemInfo IconExitInfo
            {
                get
                {
                    return _iconexitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}