///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BambooTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BambooTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("b24f02f0-15cd-4841-b040-51634afbe633")]
    public partial class BambooTestRepository : RepoGenBaseFolder
    {
        static BambooTestRepository instance = new BambooTestRepository();
        BambooTestRepositoryFolders.DownloadRanorexComAppFolder _downloadranorexcom;

        /// <summary>
        /// Gets the singleton class instance representing the BambooTestRepository element repository.
        /// </summary>
        [RepositoryFolder("b24f02f0-15cd-4841-b040-51634afbe633")]
        public static BambooTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BambooTestRepository() 
            : base("BambooTestRepository", "/", null, 0, false, "b24f02f0-15cd-4841-b040-51634afbe633", ".\\RepositoryImages\\BambooTestRepositoryb24f02f0.rximgres")
        {
            _downloadranorexcom = new BambooTestRepositoryFolders.DownloadRanorexComAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b24f02f0-15cd-4841-b040-51634afbe633")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DownloadRanorexCom folder.
        /// </summary>
        [RepositoryFolder("b6cc96c8-9cff-4965-865a-045ec37a6c54")]
        public virtual BambooTestRepositoryFolders.DownloadRanorexComAppFolder DownloadRanorexCom
        {
            get { return _downloadranorexcom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class BambooTestRepositoryFolders
    {
        /// <summary>
        /// The DownloadRanorexComAppFolder folder.
        /// </summary>
        [RepositoryFolder("b6cc96c8-9cff-4965-865a-045ec37a6c54")]
        public partial class DownloadRanorexComAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstcomboboxInfo;
            RepoItemInfo _secondcomboboxInfo;

            /// <summary>
            /// Creates a new DownloadRanorexCom  folder.
            /// </summary>
            public DownloadRanorexComAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DownloadRanorexCom", "/dom[@domain='download.ranorex.com']", parentFolder, 30000, null, false, "b6cc96c8-9cff-4965-865a-045ec37a6c54", "")
            {
                _firstcomboboxInfo = new RepoItemInfo(this, "FirstCombobox", ".//select[#'firstCombobox']", 30000, null, "e7f0e528-dd95-4090-8de6-e23e927ce4e6");
                _secondcomboboxInfo = new RepoItemInfo(this, "SecondCombobox", ".//select[#'secondCombobox']", 30000, null, "d6cb85f4-a034-4313-8115-b680fe49bc6d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b6cc96c8-9cff-4965-865a-045ec37a6c54")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b6cc96c8-9cff-4965-865a-045ec37a6c54")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstCombobox item.
            /// </summary>
            [RepositoryItem("e7f0e528-dd95-4090-8de6-e23e927ce4e6")]
            public virtual Ranorex.SelectTag FirstCombobox
            {
                get
                {
                    return _firstcomboboxInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FirstCombobox item info.
            /// </summary>
            [RepositoryItemInfo("e7f0e528-dd95-4090-8de6-e23e927ce4e6")]
            public virtual RepoItemInfo FirstComboboxInfo
            {
                get
                {
                    return _firstcomboboxInfo;
                }
            }

            /// <summary>
            /// The SecondCombobox item.
            /// </summary>
            [RepositoryItem("d6cb85f4-a034-4313-8115-b680fe49bc6d")]
            public virtual Ranorex.SelectTag SecondCombobox
            {
                get
                {
                    return _secondcomboboxInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SecondCombobox item info.
            /// </summary>
            [RepositoryItemInfo("d6cb85f4-a034-4313-8115-b680fe49bc6d")]
            public virtual RepoItemInfo SecondComboboxInfo
            {
                get
                {
                    return _secondcomboboxInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}