///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BambooTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FillRegisterForm recording.
    /// </summary>
    [TestModule("0d0789d0-3bd6-49bf-b422-efcafa58183e", ModuleType.Recording, 1)]
    public partial class FillRegisterForm : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BambooTestRepository repository.
        /// </summary>
        public static BambooTestRepository repo = BambooTestRepository.Instance;

        static FillRegisterForm instance = new FillRegisterForm();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FillRegisterForm()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FillRegisterForm Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexWebpage.FormFirstName' at Center.", repo.RanorexWebpage.FormFirstNameInfo, new RecordItemIndex(0));
            repo.RanorexWebpage.FormFirstName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'John' with focus on 'RanorexWebpage.FormFirstName'.", repo.RanorexWebpage.FormFirstNameInfo, new RecordItemIndex(1));
            repo.RanorexWebpage.FormFirstName.PressKeys("John");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexWebpage.FormLastName' at Center.", repo.RanorexWebpage.FormLastNameInfo, new RecordItemIndex(2));
            repo.RanorexWebpage.FormLastName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Doe' with focus on 'RanorexWebpage.FormLastName'.", repo.RanorexWebpage.FormLastNameInfo, new RecordItemIndex(3));
            repo.RanorexWebpage.FormLastName.PressKeys("Doe");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexWebpage.FormEmail' at Center.", repo.RanorexWebpage.FormEmailInfo, new RecordItemIndex(4));
            repo.RanorexWebpage.FormEmail.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'john@doe.com' with focus on 'RanorexWebpage.FormEmail'.", repo.RanorexWebpage.FormEmailInfo, new RecordItemIndex(5));
            repo.RanorexWebpage.FormEmail.PressKeys("john@doe.com");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
